---
# =============================================================================
# Development Tools Role - Metadata
# =============================================================================

galaxy_info:
  author: Brian Grimmett
  description: Install and configure development and automation tools
  company: Starbase Engineering
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: MacOSX
      versions:
        - all
  galaxy_tags:
    - macos
    - development
    - git
    - automation
    - tools

dependencies:
  - role: homebrew
